#!/usr/bin/env bash
# Dump AM's authentication node catalog into a static reference file shared by
# agent skills.
#
# Output: agent/skills/_references/am-node-catalog.json
#   {
#     "_meta": { generatedAt, amVersion, forgeopsRef, nodeCount },
#     "types": {
#       "<NodeTypeId>": {
#         "name": "...",
#         "tags": [...],
#         "help": "...",
#         "config": {
#           "required": [...],
#           "properties": { fieldName: { type, title, description } }
#         }
#       },
#       ...
#     }
#   }
#
# What this DOES capture: type metadata + config-field schema (what to put
# inside upsert_node's `config` blob).
# What this does NOT capture: outcome names. Outcomes can be data-dependent
# (ChoiceCollectorNode emits user-configured outcomes), so they live in the
# hand-curated agent/skills/_references/am-node-outcomes.md alongside.
#
# Idempotent — re-run after each forgeops upgrade to catch new node types.

source "$(dirname "$0")/lib.sh"
require curl jq kubectl

OUT_DIR="${REPO_ROOT}/agent/skills/_references"
OUT_FILE="${OUT_DIR}/am-node-catalog.json"
mkdir -p "$OUT_DIR"

AM_BASE="https://${FQDN}/am"
AM_REALM="$(grep -E '^AM_REALM=' "$SERVER_ENV_FILE" 2>/dev/null | tail -1 | cut -d= -f2- | tr -d '"' | awk '{print $1}')"
AM_REALM="${AM_REALM:-root}"
if [[ "$AM_REALM" == "root" || -z "$AM_REALM" ]]; then
  REALM_PATH="root"
else
  REALM_PATH="root/realms/${AM_REALM}"
fi
NODES_URL="${AM_BASE}/json/realms/${REALM_PATH}/realm-config/authentication/authenticationtrees/nodes"

AM_ADMIN_PASSWORD=$(kubectl get secret am-env-secrets -n "$NAMESPACE" \
  -o jsonpath='{.data.AM_PASSWORDS_AMADMIN_CLEAR}' | base64 -d)
[[ -n "$AM_ADMIN_PASSWORD" ]] || { err "could not fetch amadmin password"; exit 1; }

COOKIE=$(curl -sk "${AM_BASE}/json/serverinfo/*" | jq -r .cookieName)
[[ -n "$COOKIE" && "$COOKIE" != "null" ]] || { err "cannot reach AM at ${AM_BASE}"; exit 1; }

log "Logging in as amadmin"
TOKEN=$(curl -sk -X POST "${AM_BASE}/json/realms/root/authenticate" \
  -H "X-OpenAM-Username: ${AM_ADMIN_USER}" \
  -H "X-OpenAM-Password: ${AM_ADMIN_PASSWORD}" \
  -H "Accept-API-Version: resource=2.0, protocol=1.0" | jq -r .tokenId)
[[ -n "$TOKEN" && "$TOKEN" != "null" ]] || { err "amadmin login failed"; exit 1; }

auth_hdr=(-H "${COOKIE}: ${TOKEN}" -H "Accept-API-Version: protocol=2.1, resource=1.0")

log "Fetching node-type catalog (?_action=getAllTypes)"
ALL_TYPES=$(curl -sk -X POST "${NODES_URL}?_action=getAllTypes" \
  "${auth_hdr[@]}" -H "Content-Type: application/json" -d '{}')
TYPE_COUNT=$(echo "$ALL_TYPES" | jq '.result | length')
log "AM exposes ${TYPE_COUNT} node types"

# Build the per-type schema map. Iterate types and merge schema into each.
log "Fetching per-type schemas (one request each — slow but only run on rebuild)"
TYPES_JSON='{}'
i=0
while IFS= read -r type_id; do
  i=$((i + 1))
  printf '\r  [%3d/%3d] %s%-60s' "$i" "$TYPE_COUNT" "" "$type_id"
  meta=$(echo "$ALL_TYPES" | jq --arg t "$type_id" '.result[] | select(._id == $t)')
  schema=$(curl -sk -X POST "${NODES_URL}/${type_id}?_action=schema" \
    "${auth_hdr[@]}" -H "Content-Type: application/json" -d '{}')
  entry=$(jq -n \
    --argjson m "$meta" \
    --argjson s "$schema" \
    '{
       name:    $m.name,
       tags:    ($m.tags // []),
       help:    ($m.help // ""),
       config: {
         required:   ($s.required   // []),
         properties: ($s.properties // {}),
       }
     }')
  TYPES_JSON=$(jq --arg t "$type_id" --argjson e "$entry" '.[$t] = $e' <<<"$TYPES_JSON")
done < <(echo "$ALL_TYPES" | jq -r '.result[]._id')
echo

GENERATED_AT=$(date -u +%Y-%m-%dT%H:%M:%SZ)
PLATFORM_VERSION_VAL="${PLATFORM_VERSION:-unknown}"
FORGEOPS_REF_VAL="${FORGEOPS_REF:-unknown}"

jq -n \
  --arg generatedAt "$GENERATED_AT" \
  --arg platformVersion "$PLATFORM_VERSION_VAL" \
  --arg forgeopsRef "$FORGEOPS_REF_VAL" \
  --argjson types "$TYPES_JSON" \
  '{
     _meta: {
       generatedAt:     $generatedAt,
       platformVersion: $platformVersion,
       forgeopsRef:     $forgeopsRef,
       nodeCount:       ($types | length),
       note:            "Generated by ops/scripts/dump-node-catalog.sh. Outcome names live in am-node-outcomes.md (hand-curated; some are data-dependent and cant come from REST)."
     },
     types: $types
   }' > "$OUT_FILE"

ok "wrote $OUT_FILE ($(jq '._meta.nodeCount' "$OUT_FILE") types, $(wc -c < "$OUT_FILE" | tr -d ' ') bytes)"
